# Copyright 2025 Notedown Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2

project_name: notedown-language-server

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: notedown-language-server
    main: ./language-server/
    binary: notedown-language-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/notedownorg/notedown/pkg/version.Version={{.Version}}
      - -X github.com/notedownorg/notedown/pkg/version.Commit={{.Commit}}
      - -X github.com/notedownorg/notedown/pkg/version.Date={{.Date}}
      - -X github.com/notedownorg/notedown/pkg/version.BuiltBy=goreleaser

archives:
  - id: notedown-language-server
    builds:
      - notedown-language-server
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.MD
      - LICENSE

checksum:
  name_template: 'checksums.txt'


snapshot:
  version_template: "{{ .Env.NIGHTLY_VERSION }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^refactor:'
      - '^style:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999

release:
  disable: true

# Disable unwanted features for nightly builds
brews: []
dockers: []
nfpms: []
publishers: []
milestones: []