// Copyright 2025 Notedown Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: application_server/v1alpha1/document_service.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetadataOperator defines comparison operators for metadata filtering
type MetadataOperator int32

const (
	MetadataOperator_METADATA_OPERATOR_UNSPECIFIED MetadataOperator = 0
	// Equality operators
	MetadataOperator_METADATA_OPERATOR_EQUALS     MetadataOperator = 1
	MetadataOperator_METADATA_OPERATOR_NOT_EQUALS MetadataOperator = 2
	// String operators
	MetadataOperator_METADATA_OPERATOR_CONTAINS    MetadataOperator = 3
	MetadataOperator_METADATA_OPERATOR_STARTS_WITH MetadataOperator = 4
	MetadataOperator_METADATA_OPERATOR_ENDS_WITH   MetadataOperator = 5
	// Numeric operators
	MetadataOperator_METADATA_OPERATOR_GREATER_THAN          MetadataOperator = 6
	MetadataOperator_METADATA_OPERATOR_GREATER_THAN_OR_EQUAL MetadataOperator = 7
	MetadataOperator_METADATA_OPERATOR_LESS_THAN             MetadataOperator = 8
	MetadataOperator_METADATA_OPERATOR_LESS_THAN_OR_EQUAL    MetadataOperator = 9
	// Array operators
	MetadataOperator_METADATA_OPERATOR_IN     MetadataOperator = 10
	MetadataOperator_METADATA_OPERATOR_NOT_IN MetadataOperator = 11
	// Existence operators
	MetadataOperator_METADATA_OPERATOR_EXISTS     MetadataOperator = 12
	MetadataOperator_METADATA_OPERATOR_NOT_EXISTS MetadataOperator = 13
)

// Enum value maps for MetadataOperator.
var (
	MetadataOperator_name = map[int32]string{
		0:  "METADATA_OPERATOR_UNSPECIFIED",
		1:  "METADATA_OPERATOR_EQUALS",
		2:  "METADATA_OPERATOR_NOT_EQUALS",
		3:  "METADATA_OPERATOR_CONTAINS",
		4:  "METADATA_OPERATOR_STARTS_WITH",
		5:  "METADATA_OPERATOR_ENDS_WITH",
		6:  "METADATA_OPERATOR_GREATER_THAN",
		7:  "METADATA_OPERATOR_GREATER_THAN_OR_EQUAL",
		8:  "METADATA_OPERATOR_LESS_THAN",
		9:  "METADATA_OPERATOR_LESS_THAN_OR_EQUAL",
		10: "METADATA_OPERATOR_IN",
		11: "METADATA_OPERATOR_NOT_IN",
		12: "METADATA_OPERATOR_EXISTS",
		13: "METADATA_OPERATOR_NOT_EXISTS",
	}
	MetadataOperator_value = map[string]int32{
		"METADATA_OPERATOR_UNSPECIFIED":           0,
		"METADATA_OPERATOR_EQUALS":                1,
		"METADATA_OPERATOR_NOT_EQUALS":            2,
		"METADATA_OPERATOR_CONTAINS":              3,
		"METADATA_OPERATOR_STARTS_WITH":           4,
		"METADATA_OPERATOR_ENDS_WITH":             5,
		"METADATA_OPERATOR_GREATER_THAN":          6,
		"METADATA_OPERATOR_GREATER_THAN_OR_EQUAL": 7,
		"METADATA_OPERATOR_LESS_THAN":             8,
		"METADATA_OPERATOR_LESS_THAN_OR_EQUAL":    9,
		"METADATA_OPERATOR_IN":                    10,
		"METADATA_OPERATOR_NOT_IN":                11,
		"METADATA_OPERATOR_EXISTS":                12,
		"METADATA_OPERATOR_NOT_EXISTS":            13,
	}
)

func (x MetadataOperator) Enum() *MetadataOperator {
	p := new(MetadataOperator)
	*p = x
	return p
}

func (x MetadataOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_application_server_v1alpha1_document_service_proto_enumTypes[0].Descriptor()
}

func (MetadataOperator) Type() protoreflect.EnumType {
	return &file_application_server_v1alpha1_document_service_proto_enumTypes[0]
}

func (x MetadataOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataOperator.Descriptor instead.
func (MetadataOperator) EnumDescriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{0}
}

// ListDocumentsRequest defines the request for listing documents
type ListDocumentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter defines the criteria for filtering documents
	Filter        *FilterExpression `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListDocumentsRequest) GetFilter() *FilterExpression {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ListDocumentsResponse contains the filtered documents
type ListDocumentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Documents that match the filter criteria
	Documents     []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Document represents a Notedown Flavored Markdown document
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path is the relative path from workspace root
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Checksum is a hash of the document content for change detection
	Checksum string `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Metadata contains the frontmatter metadata as key-value pairs
	Metadata *structpb.Struct `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Wikilinks found in the document
	Wikilinks []*Wikilink `protobuf:"bytes,5,rep,name=wikilinks,proto3" json:"wikilinks,omitempty"`
	// Tasks found in the document
	Tasks         []*Task `protobuf:"bytes,6,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{2}
}

func (x *Document) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Document) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Document) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Document) GetWikilinks() []*Wikilink {
	if x != nil {
		return x.Wikilinks
	}
	return nil
}

func (x *Document) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// FilterExpression represents a filtering expression for documents
type FilterExpression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expression:
	//
	//	*FilterExpression_MetadataFilter
	//	*FilterExpression_AndFilter
	//	*FilterExpression_OrFilter
	//	*FilterExpression_NotFilter
	Expression    isFilterExpression_Expression `protobuf_oneof:"expression"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterExpression) Reset() {
	*x = FilterExpression{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterExpression) ProtoMessage() {}

func (x *FilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterExpression.ProtoReflect.Descriptor instead.
func (*FilterExpression) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{3}
}

func (x *FilterExpression) GetExpression() isFilterExpression_Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

func (x *FilterExpression) GetMetadataFilter() *MetadataFilter {
	if x != nil {
		if x, ok := x.Expression.(*FilterExpression_MetadataFilter); ok {
			return x.MetadataFilter
		}
	}
	return nil
}

func (x *FilterExpression) GetAndFilter() *AndFilter {
	if x != nil {
		if x, ok := x.Expression.(*FilterExpression_AndFilter); ok {
			return x.AndFilter
		}
	}
	return nil
}

func (x *FilterExpression) GetOrFilter() *OrFilter {
	if x != nil {
		if x, ok := x.Expression.(*FilterExpression_OrFilter); ok {
			return x.OrFilter
		}
	}
	return nil
}

func (x *FilterExpression) GetNotFilter() *NotFilter {
	if x != nil {
		if x, ok := x.Expression.(*FilterExpression_NotFilter); ok {
			return x.NotFilter
		}
	}
	return nil
}

type isFilterExpression_Expression interface {
	isFilterExpression_Expression()
}

type FilterExpression_MetadataFilter struct {
	// MetadataFilter filters documents based on frontmatter metadata
	MetadataFilter *MetadataFilter `protobuf:"bytes,1,opt,name=metadata_filter,json=metadataFilter,proto3,oneof"`
}

type FilterExpression_AndFilter struct {
	// AndFilter combines multiple filters with AND logic
	AndFilter *AndFilter `protobuf:"bytes,2,opt,name=and_filter,json=andFilter,proto3,oneof"`
}

type FilterExpression_OrFilter struct {
	// OrFilter combines multiple filters with OR logic
	OrFilter *OrFilter `protobuf:"bytes,3,opt,name=or_filter,json=orFilter,proto3,oneof"`
}

type FilterExpression_NotFilter struct {
	// NotFilter negates a filter
	NotFilter *NotFilter `protobuf:"bytes,4,opt,name=not_filter,json=notFilter,proto3,oneof"`
}

func (*FilterExpression_MetadataFilter) isFilterExpression_Expression() {}

func (*FilterExpression_AndFilter) isFilterExpression_Expression() {}

func (*FilterExpression_OrFilter) isFilterExpression_Expression() {}

func (*FilterExpression_NotFilter) isFilterExpression_Expression() {}

// MetadataFilter filters documents based on frontmatter metadata
type MetadataFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field is the metadata field name to filter on
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Operator defines how to compare the field value
	Operator MetadataOperator `protobuf:"varint,2,opt,name=operator,proto3,enum=notedown.application_server.v1alpha1.MetadataOperator" json:"operator,omitempty"`
	// Value is the value to compare against (type depends on comparison)
	Value         *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataFilter) Reset() {
	*x = MetadataFilter{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataFilter) ProtoMessage() {}

func (x *MetadataFilter) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataFilter.ProtoReflect.Descriptor instead.
func (*MetadataFilter) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{4}
}

func (x *MetadataFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *MetadataFilter) GetOperator() MetadataOperator {
	if x != nil {
		return x.Operator
	}
	return MetadataOperator_METADATA_OPERATOR_UNSPECIFIED
}

func (x *MetadataFilter) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// AndFilter combines multiple filters with AND logic
type AndFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*FilterExpression    `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndFilter) Reset() {
	*x = AndFilter{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndFilter) ProtoMessage() {}

func (x *AndFilter) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndFilter.ProtoReflect.Descriptor instead.
func (*AndFilter) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{5}
}

func (x *AndFilter) GetFilters() []*FilterExpression {
	if x != nil {
		return x.Filters
	}
	return nil
}

// OrFilter combines multiple filters with OR logic
type OrFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*FilterExpression    `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrFilter) Reset() {
	*x = OrFilter{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrFilter) ProtoMessage() {}

func (x *OrFilter) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrFilter.ProtoReflect.Descriptor instead.
func (*OrFilter) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{6}
}

func (x *OrFilter) GetFilters() []*FilterExpression {
	if x != nil {
		return x.Filters
	}
	return nil
}

// NotFilter negates a filter
type NotFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *FilterExpression      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFilter) Reset() {
	*x = NotFilter{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFilter) ProtoMessage() {}

func (x *NotFilter) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFilter.ProtoReflect.Descriptor instead.
func (*NotFilter) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{7}
}

func (x *NotFilter) GetFilter() *FilterExpression {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Wikilink represents a wikilink found in a document
type Wikilink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target is the wikilink target (e.g., "project-alpha", "docs/api")
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// DisplayText is the display text if pipe notation is used
	DisplayText string `protobuf:"bytes,2,opt,name=display_text,json=displayText,proto3" json:"display_text,omitempty"`
	// Line is the 1-based line number where the wikilink appears
	Line int32 `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	// Column is the 1-based column number where the wikilink appears
	Column        int32 `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wikilink) Reset() {
	*x = Wikilink{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wikilink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wikilink) ProtoMessage() {}

func (x *Wikilink) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wikilink.ProtoReflect.Descriptor instead.
func (*Wikilink) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{8}
}

func (x *Wikilink) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Wikilink) GetDisplayText() string {
	if x != nil {
		return x.DisplayText
	}
	return ""
}

func (x *Wikilink) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Wikilink) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Task represents a task found in a document
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State is the raw state value (e.g., " ", "x", "wip", "in-progress")
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Text is the task description text
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Line is the 1-based line number where the task appears
	Line int32 `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	// Column is the 1-based column number where the task appears
	Column        int32 `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_application_server_v1alpha1_document_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_application_server_v1alpha1_document_service_proto_rawDescGZIP(), []int{9}
}

func (x *Task) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Task) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Task) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Task) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

var File_application_server_v1alpha1_document_service_proto protoreflect.FileDescriptor

const file_application_server_v1alpha1_document_service_proto_rawDesc = "" +
	"\n" +
	"2application_server/v1alpha1/document_service.proto\x12$notedown.application_server.v1alpha1\x1a\x1cgoogle/protobuf/struct.proto\"f\n" +
	"\x14ListDocumentsRequest\x12N\n" +
	"\x06filter\x18\x01 \x01(\v26.notedown.application_server.v1alpha1.FilterExpressionR\x06filter\"e\n" +
	"\x15ListDocumentsResponse\x12L\n" +
	"\tdocuments\x18\x01 \x03(\v2..notedown.application_server.v1alpha1.DocumentR\tdocuments\"\xff\x01\n" +
	"\bDocument\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12L\n" +
	"\twikilinks\x18\x05 \x03(\v2..notedown.application_server.v1alpha1.WikilinkR\twikilinks\x12@\n" +
	"\x05tasks\x18\x06 \x03(\v2*.notedown.application_server.v1alpha1.TaskR\x05tasks\"\xf4\x02\n" +
	"\x10FilterExpression\x12_\n" +
	"\x0fmetadata_filter\x18\x01 \x01(\v24.notedown.application_server.v1alpha1.MetadataFilterH\x00R\x0emetadataFilter\x12P\n" +
	"\n" +
	"and_filter\x18\x02 \x01(\v2/.notedown.application_server.v1alpha1.AndFilterH\x00R\tandFilter\x12M\n" +
	"\tor_filter\x18\x03 \x01(\v2..notedown.application_server.v1alpha1.OrFilterH\x00R\borFilter\x12P\n" +
	"\n" +
	"not_filter\x18\x04 \x01(\v2/.notedown.application_server.v1alpha1.NotFilterH\x00R\tnotFilterB\f\n" +
	"\n" +
	"expression\"\xa8\x01\n" +
	"\x0eMetadataFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12R\n" +
	"\boperator\x18\x02 \x01(\x0e26.notedown.application_server.v1alpha1.MetadataOperatorR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"]\n" +
	"\tAndFilter\x12P\n" +
	"\afilters\x18\x01 \x03(\v26.notedown.application_server.v1alpha1.FilterExpressionR\afilters\"\\\n" +
	"\bOrFilter\x12P\n" +
	"\afilters\x18\x01 \x03(\v26.notedown.application_server.v1alpha1.FilterExpressionR\afilters\"[\n" +
	"\tNotFilter\x12N\n" +
	"\x06filter\x18\x01 \x01(\v26.notedown.application_server.v1alpha1.FilterExpressionR\x06filter\"q\n" +
	"\bWikilink\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12!\n" +
	"\fdisplay_text\x18\x02 \x01(\tR\vdisplayText\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"\\\n" +
	"\x04Task\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column*\xed\x03\n" +
	"\x10MetadataOperator\x12!\n" +
	"\x1dMETADATA_OPERATOR_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18METADATA_OPERATOR_EQUALS\x10\x01\x12 \n" +
	"\x1cMETADATA_OPERATOR_NOT_EQUALS\x10\x02\x12\x1e\n" +
	"\x1aMETADATA_OPERATOR_CONTAINS\x10\x03\x12!\n" +
	"\x1dMETADATA_OPERATOR_STARTS_WITH\x10\x04\x12\x1f\n" +
	"\x1bMETADATA_OPERATOR_ENDS_WITH\x10\x05\x12\"\n" +
	"\x1eMETADATA_OPERATOR_GREATER_THAN\x10\x06\x12+\n" +
	"'METADATA_OPERATOR_GREATER_THAN_OR_EQUAL\x10\a\x12\x1f\n" +
	"\x1bMETADATA_OPERATOR_LESS_THAN\x10\b\x12(\n" +
	"$METADATA_OPERATOR_LESS_THAN_OR_EQUAL\x10\t\x12\x18\n" +
	"\x14METADATA_OPERATOR_IN\x10\n" +
	"\x12\x1c\n" +
	"\x18METADATA_OPERATOR_NOT_IN\x10\v\x12\x1c\n" +
	"\x18METADATA_OPERATOR_EXISTS\x10\f\x12 \n" +
	"\x1cMETADATA_OPERATOR_NOT_EXISTS\x10\r2\x9c\x01\n" +
	"\x0fDocumentService\x12\x88\x01\n" +
	"\rListDocuments\x12:.notedown.application_server.v1alpha1.ListDocumentsRequest\x1a;.notedown.application_server.v1alpha1.ListDocumentsResponseBNZLgithub.com/notedownorg/notedown/apis/go/application_server/v1alpha1;v1alpha1b\x06proto3"

var (
	file_application_server_v1alpha1_document_service_proto_rawDescOnce sync.Once
	file_application_server_v1alpha1_document_service_proto_rawDescData []byte
)

func file_application_server_v1alpha1_document_service_proto_rawDescGZIP() []byte {
	file_application_server_v1alpha1_document_service_proto_rawDescOnce.Do(func() {
		file_application_server_v1alpha1_document_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_server_v1alpha1_document_service_proto_rawDesc), len(file_application_server_v1alpha1_document_service_proto_rawDesc)))
	})
	return file_application_server_v1alpha1_document_service_proto_rawDescData
}

var file_application_server_v1alpha1_document_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_application_server_v1alpha1_document_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_application_server_v1alpha1_document_service_proto_goTypes = []any{
	(MetadataOperator)(0),         // 0: notedown.application_server.v1alpha1.MetadataOperator
	(*ListDocumentsRequest)(nil),  // 1: notedown.application_server.v1alpha1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil), // 2: notedown.application_server.v1alpha1.ListDocumentsResponse
	(*Document)(nil),              // 3: notedown.application_server.v1alpha1.Document
	(*FilterExpression)(nil),      // 4: notedown.application_server.v1alpha1.FilterExpression
	(*MetadataFilter)(nil),        // 5: notedown.application_server.v1alpha1.MetadataFilter
	(*AndFilter)(nil),             // 6: notedown.application_server.v1alpha1.AndFilter
	(*OrFilter)(nil),              // 7: notedown.application_server.v1alpha1.OrFilter
	(*NotFilter)(nil),             // 8: notedown.application_server.v1alpha1.NotFilter
	(*Wikilink)(nil),              // 9: notedown.application_server.v1alpha1.Wikilink
	(*Task)(nil),                  // 10: notedown.application_server.v1alpha1.Task
	(*structpb.Struct)(nil),       // 11: google.protobuf.Struct
	(*structpb.Value)(nil),        // 12: google.protobuf.Value
}
var file_application_server_v1alpha1_document_service_proto_depIdxs = []int32{
	4,  // 0: notedown.application_server.v1alpha1.ListDocumentsRequest.filter:type_name -> notedown.application_server.v1alpha1.FilterExpression
	3,  // 1: notedown.application_server.v1alpha1.ListDocumentsResponse.documents:type_name -> notedown.application_server.v1alpha1.Document
	11, // 2: notedown.application_server.v1alpha1.Document.metadata:type_name -> google.protobuf.Struct
	9,  // 3: notedown.application_server.v1alpha1.Document.wikilinks:type_name -> notedown.application_server.v1alpha1.Wikilink
	10, // 4: notedown.application_server.v1alpha1.Document.tasks:type_name -> notedown.application_server.v1alpha1.Task
	5,  // 5: notedown.application_server.v1alpha1.FilterExpression.metadata_filter:type_name -> notedown.application_server.v1alpha1.MetadataFilter
	6,  // 6: notedown.application_server.v1alpha1.FilterExpression.and_filter:type_name -> notedown.application_server.v1alpha1.AndFilter
	7,  // 7: notedown.application_server.v1alpha1.FilterExpression.or_filter:type_name -> notedown.application_server.v1alpha1.OrFilter
	8,  // 8: notedown.application_server.v1alpha1.FilterExpression.not_filter:type_name -> notedown.application_server.v1alpha1.NotFilter
	0,  // 9: notedown.application_server.v1alpha1.MetadataFilter.operator:type_name -> notedown.application_server.v1alpha1.MetadataOperator
	12, // 10: notedown.application_server.v1alpha1.MetadataFilter.value:type_name -> google.protobuf.Value
	4,  // 11: notedown.application_server.v1alpha1.AndFilter.filters:type_name -> notedown.application_server.v1alpha1.FilterExpression
	4,  // 12: notedown.application_server.v1alpha1.OrFilter.filters:type_name -> notedown.application_server.v1alpha1.FilterExpression
	4,  // 13: notedown.application_server.v1alpha1.NotFilter.filter:type_name -> notedown.application_server.v1alpha1.FilterExpression
	1,  // 14: notedown.application_server.v1alpha1.DocumentService.ListDocuments:input_type -> notedown.application_server.v1alpha1.ListDocumentsRequest
	2,  // 15: notedown.application_server.v1alpha1.DocumentService.ListDocuments:output_type -> notedown.application_server.v1alpha1.ListDocumentsResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_application_server_v1alpha1_document_service_proto_init() }
func file_application_server_v1alpha1_document_service_proto_init() {
	if File_application_server_v1alpha1_document_service_proto != nil {
		return
	}
	file_application_server_v1alpha1_document_service_proto_msgTypes[3].OneofWrappers = []any{
		(*FilterExpression_MetadataFilter)(nil),
		(*FilterExpression_AndFilter)(nil),
		(*FilterExpression_OrFilter)(nil),
		(*FilterExpression_NotFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_server_v1alpha1_document_service_proto_rawDesc), len(file_application_server_v1alpha1_document_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_server_v1alpha1_document_service_proto_goTypes,
		DependencyIndexes: file_application_server_v1alpha1_document_service_proto_depIdxs,
		EnumInfos:         file_application_server_v1alpha1_document_service_proto_enumTypes,
		MessageInfos:      file_application_server_v1alpha1_document_service_proto_msgTypes,
	}.Build()
	File_application_server_v1alpha1_document_service_proto = out.File
	file_application_server_v1alpha1_document_service_proto_goTypes = nil
	file_application_server_v1alpha1_document_service_proto_depIdxs = nil
}
