/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_POUND = 2,
  aux_sym_heading_token1 = 3,
  anon_sym_LBRACK_LBRACK = 4,
  anon_sym_RBRACK_RBRACK = 5,
  anon_sym_PIPE = 6,
  sym_wikilink_target = 7,
  sym_wikilink_display = 8,
  sym_text = 9,
  sym_document = 10,
  sym__content = 11,
  sym_heading = 12,
  sym_wikilink = 13,
  aux_sym_document_repeat1 = 14,
  aux_sym_heading_repeat1 = 15,
  aux_sym_heading_repeat2 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND] = "#",
  [aux_sym_heading_token1] = "heading_token1",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [anon_sym_PIPE] = "|",
  [sym_wikilink_target] = "wikilink_target",
  [sym_wikilink_display] = "wikilink_display",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__content] = "_content",
  [sym_heading] = "heading",
  [sym_wikilink] = "wikilink",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_heading_repeat1] = "heading_repeat1",
  [aux_sym_heading_repeat2] = "heading_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_heading_token1] = aux_sym_heading_token1,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_wikilink_target] = sym_wikilink_target,
  [sym_wikilink_display] = sym_wikilink_display,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__content] = sym__content,
  [sym_heading] = sym_heading,
  [sym_wikilink] = sym_wikilink,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_heading_repeat1] = aux_sym_heading_repeat1,
  [aux_sym_heading_repeat2] = aux_sym_heading_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_heading_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_wikilink_target] = {
    .visible = true,
    .named = true,
  },
  [sym_wikilink_display] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_wikilink] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_display = 2,
  field_level = 3,
  field_target = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_display] = "display",
  [field_level] = "level",
  [field_target] = "target",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_level, 0},
  [1] =
    {field_target, 1},
  [2] =
    {field_content, 2},
    {field_level, 0},
  [4] =
    {field_display, 3},
    {field_target, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '[') ADVANCE(2);
      if (lookahead == ']') ADVANCE(3);
      if (lookahead == '|') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '[') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == ']') ADVANCE(12);
      END_STATE();
    case 4:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(15);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(17);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '[') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(19);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_wikilink_target);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_wikilink_target);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_wikilink_display);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_wikilink_display);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(13),
    [sym__content] = STATE(2),
    [sym_heading] = STATE(2),
    [sym_wikilink] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_heading_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(9),
    [sym_text] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__content] = STATE(3),
    [sym_heading] = STATE(3),
    [sym_wikilink] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_heading_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(9),
    [sym_text] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__content] = STATE(3),
    [sym_heading] = STATE(3),
    [sym_wikilink] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_heading_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(20),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(23),
    [sym_text] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    ACTIONS(30), 1,
      sym_text,
    ACTIONS(28), 2,
      anon_sym_LF,
      anon_sym_POUND,
    STATE(5), 2,
      sym_wikilink,
      aux_sym_heading_repeat2,
  [18] = 5,
    ACTIONS(9), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      sym_text,
    ACTIONS(34), 2,
      anon_sym_LF,
      anon_sym_POUND,
    STATE(6), 2,
      sym_wikilink,
      aux_sym_heading_repeat2,
  [36] = 5,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(45), 1,
      sym_text,
    ACTIONS(40), 2,
      anon_sym_LF,
      anon_sym_POUND,
    STATE(6), 2,
      sym_wikilink,
      aux_sym_heading_repeat2,
  [54] = 2,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_LBRACK_LBRACK,
      sym_text,
  [64] = 2,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 4,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_LBRACK_LBRACK,
      sym_text,
  [74] = 3,
    ACTIONS(56), 1,
      anon_sym_POUND,
    ACTIONS(58), 1,
      aux_sym_heading_token1,
    STATE(10), 1,
      aux_sym_heading_repeat1,
  [84] = 3,
    ACTIONS(60), 1,
      anon_sym_POUND,
    ACTIONS(63), 1,
      aux_sym_heading_token1,
    STATE(10), 1,
      aux_sym_heading_repeat1,
  [94] = 2,
    ACTIONS(65), 1,
      anon_sym_RBRACK_RBRACK,
    ACTIONS(67), 1,
      anon_sym_PIPE,
  [101] = 1,
    ACTIONS(69), 1,
      sym_wikilink_target,
  [105] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [109] = 1,
    ACTIONS(73), 1,
      sym_wikilink_display,
  [113] = 1,
    ACTIONS(75), 1,
      anon_sym_RBRACK_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 64,
  [SMALL_STATE(9)] = 74,
  [SMALL_STATE(10)] = 84,
  [SMALL_STATE(11)] = 94,
  [SMALL_STATE(12)] = 101,
  [SMALL_STATE(13)] = 105,
  [SMALL_STATE(14)] = 109,
  [SMALL_STATE(15)] = 113,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2, 0, 1),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 2, 0, 1),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 3),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 3),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_repeat2, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_heading_repeat2, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat2, 2, 0, 0), SHIFT_REPEAT(12),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wikilink, 3, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wikilink, 3, 0, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wikilink, 5, 0, 4),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wikilink, 5, 0, 4),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_notedown(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "notedown",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
