name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Install Licenser
      run: go install github.com/liamawhite/licenser@21016ac7e79acc475e3b11f71aac7499a21790a5

    - run: make hygiene
    - run: make dirty

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Install dictionary for babbler library
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y wamerican

    # These are required as we create >10k directories as part of testing 
    - name: Increase open file limit for macOS
      if: matrix.os == 'macos-latest'
      run: |
          # I just picked the values I had on my machine (where the tests passed already)
          sudo sysctl -w kern.maxfiles=491520
          sudo sysctl -w kern.maxfilesperproc=245760

    - run: make test

    - name: Testdata upload
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: testdata-${{ matrix.os }}
        path: ${{ github.workspace }}/testdata
        if-no-files-found: error
